language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0

install:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:~1.0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  slack:
    secure: 62i7aVuG9jSoFtAb8doolePh2szh581WS/QJHQdu7MweKfML0h7iO7NgvIflVPkkXt5whZ11ficGfYrCbjxUG3zHJjdujw9tfgtbeI6NfJG8XgjZ+6sdk/Pm3LzBpgcyVnoTWffLgGmjSxadE+0YvJCsheO4e60qSRa58SFOh2MkDSS+KHY/0f257j0WXXmkdNttqpA5KzAY4a903n67J8h8eVbRqrcOn5svsiQrigWykmotHTxDNwatL+oP6w8TEGsO5r6MjHgagJ95Yydybe/qKzDEpwbHauf2TQzxr63HZcHJNVIDUP1aWIzQARETTlqCnluMfQ23EcV+AKZ4jkWI6Yp1mZONEDPfWnAgnuvbLeaDWw2u+vwnSFFblkq5/vtD0xaKM5SNO5tqGvazYtGE1GJYIrg89RLr5D4XJB1AUeRiPLhw9R3uMYlkOWkUAK1N4oERqVj+pSi9WSi06/2hscJXbCsPD/a1sVKXAAaYF58vOyI1OPu72uZDPfz53gTBBJY3/GulaT9ZqFI4FQRHNsI52E5ccNFhh5Rgn/Q4RR7BH/bvoODqQhDCzXk8Lt6KEtjmWcFH4IQt9PPsQt+u3bPrLtoOeCSejR+t5OqH4S9tFOcAdSPa17j4oFwQgeYeUlhO0HL4HQME8RLHefuwrVb5SVa+54OQ4451mk8=
