language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0

install:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:~1.0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  slack:
    secure: 4GPJ/BMHcMGSKDDBz2DYfBtJq1L4xktnHNo16B94KEqIJsUSycoJALcsIPKlj+Fgpl6urNXLVwDEecGiGvm8BjV7lpHwFQc4NAsLokYNLIQOsxYC/zzJTrs7c1CG5ysIMCXXFMklKAUluaFHJ9/KZ1I0gLqXELqGW6vpVbVro2+cqtpeZxMJszx8tIXQwwy6bdzFK3OFFKN3z3+4ddvLMEuJdasPdNdGu6IwYNRHm3FovG8HfioV/PaKGcNU/7CE8dcqfkG1Y7EQguqdKf5U/+te7x0HU/loMjRKTi/Gp5O/vbAV5KNMkPwjfoQiBocv2TfAu9NFZENS3/De1YyZ4JEKyZFGqbww1cOnI/p5oQRRNwaIAsouYT9k/HR6izVk34J02oOd5j/haVmvSBBTWwRq6KMkHWQ+90lRPqUP5ljIK8wfyv9bnSyP4+qIUzqq2P888TjTLXSP95VcnKhmVfdnEArFJBlEW5PAi8mf7veqZlUqDBBIODgIH4j+mBixzQUtvrkqpeEqxtcPKGUqfbPibymIuszMv02EBB8CLQW24LjGlbG3k2fajxjRSHGvp8mDecLdx4R0oM/WC0DTuMWIrLRxFYd9vTOAP89E28LbX9z5YBJV8GtbGfeCqo8ybnsM0dd/YKnXyVppeA7JagChOFgjMUGzZCZnys51hN4=
